name: jfdtest2
favicon: null
layout_spectrum: 0.3080089387949556
typography_spectrum: 0.4808115477208048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9888584853615612
  lightness: 0.022496311692520976
  saturation: 0.792985157109797
  rhythmicContrast: 0.5078633341472596
purpose: []
